id: P010654
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:24.377956
source_metadata:
  id: bdr:W1KG8929
  title: རྒྱུན་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    314dc9fb30e94793842d6c84a66efb1c:
      image_group_id: I1KG9005
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
